### PR TITLE
Update README.md with IAM policy

### PR DESCRIPTION
**Pull request by daverickdunn**
Added list of required resources and a sample policy.

### CODE REVIEW

**Comment by daverickdunn** [comment]
If you do decide to merge, maybe remove the condition block from the IAM policy. There appears to be a bug with IAM at the moment. 
ie. remove:

```
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "<SOURCE IP AND BITMASK>"
                }
            }
```

Cheers for the repo! I use it loads!

**Comment by ca98am79** [comment]
thanks - could you remove the condition block?  Then I will merge this request.  Thank you

**Comment by daverickdunn** [comment]
Cool. Updated.

**Comment by ca98am79** [comment]
thanks!

**Pull request merged**
