### PR TITLE
Update to V3 API

### PR DESCRIPTION
**Pull request by lancegliser**
Starting work on #71.  Just a draft for visibility as I start hacking at it.

- [X] Update documentation
- [X] Update tests
- [X] Update internals
- [ ] Merge #77 to reduce needless shift
- [X] Manual `index.d.ts` updates for options.
- [ ] Reap concerns decisions

Changes (I'd suggest squash merging to these 😅)

- v3.0.0
- @aws-sdk/client-dynamodb@^3.218.0
- Refactored client uses to v3 .send(new Command()) promises.
- Refactored DynamoDBStore.prototype.touch to return (err, {expires}) to the callback.
- Moved the table describe and creation logic into an initialize function and ensured all methods call it first to expose errors.
- Updated the client in test to create from env variables directly
- Refactored tests to use more randomized values for value, constants for sessionIds, and reduce duplication.
- Refactored tests to async with Promises so errors in callbacks could be exposed to test results.
- Added a note to the README about the costs associated with scan implementation.
- Added .idea to .gitignore to filter out WebStorm files.

### CODE REVIEW

**Comment by lancegliser** [comment]
@ca98am79 I'll try to keep to JS only, but the Types need some work too. Would you be adverse in the future to moving to `tsc`?

**Comment by ca98am79** [comment]
@lancegliser that is fine with me, thank you

**Comment by lancegliser** [comment]
@ca98am79 We're online using this for a couple weeks now via `npm pack` install. Can I help in any way to get this merged and published?

**Comment by lancegliser** [comment]
@ca98am79 Noticed an issue today trying to upgrade from 16.x to 18.x on an AWS Lambda today. I traced it back to the this branch and the package I'd built from it. Wanted to use `ScalarAttributeType.*`, and it worked on 16.x. I assume 16.x just took the property as the value so ".N" came out correct. 18.x throws an error. I pushed and updated to fix it. Would love to get this published so we can properly version!

**Comment by StefanTobler** [comment]
Agreed, can we have this reviewed and merged. It is tough to have multiple mocked AWS clients across my different application with AWS sdk different versions.

**Comment by ca98am79** [comment]
thank you, sorry for the delay

**Pull request merged**
